name: goreleaser

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write
  packages: write

env:
  REGISTRY: ghcr.io
  CORE_CHART_PATH: ./core-chart

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version: 1.24

      - name: Delete non-semver tags
        run: 'git tag -d $(git tag -l | grep -v "^v")'

      - name: Set LDFLAGS
        run: echo LDFLAGS="$(make ldflags)" >> $GITHUB_ENV

      - name: Install syft binary executable
        uses: anchore/sbom-action/download-syft@9f7302141466aa6482940f15371237e9d9f4c34a

      - name: Import GPG Key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: |
            -----BEGIN PGP PRIVATE KEY BLOCK-----

            lQdGBGgsrKQBEADRo8upRvejsXzeJr2WNxp8pYDcl50WERCsVuFN64A0Qn0JrbPt
            fae9QmYaqZxPZFHjelCQZTVLOKxuVBptRtEUk3BHsuBWO3Vq3CI5mAWQp9npqUjq
            b+HsKezcJdhLWGtpx7+47CaAx8zR07XsyGnefcrRNDTecxq56YMRs0njpbM/zdhi
            SA+INQBCsqRscd09yno0hj5FkUaL4RZqu7jUcF0Dcw9calN9kkI3AVbrWWl+RF+9
            Ba6lWkDhf9CPk+wE45oHt85VrKCWcgk4Tw9i2Xl9AoOmzKefO/OUK92i6XfTRuc9
            7uWy1SMJlwQ4GUhZmXZcfKTktKwdixx6kS0VaGAaGrg9o8lcRvINCfypDSiB+AtL
            MdM9no7KXUNRJW7pdVWf34ZWwa70PMFvLX4xnSJlhEqWGy0h72bRjp1OTo8lTLdH
            XmE8R7GHczq+cVIl09YWNEMJopJNtmIRZoxrmlZyZD/nhwE8OdyYfelB5+12Lzyt
            BZqdwlLeaOp5yKvb7TMgvVEOj/p/e1hzbfsWiDNWixXKlCYZY4SHBe0xcn54HO/x
            gBq7qVcZNo3bTGqi2wQpA65bY39lWU5OtBt/xUA6hwics1B0cG+ILYZYb8WIHW24
            L+I6GQTVqgFXOgDxgOPmwow5g3SBJFhRQkooAImZjuzKZ1kpxN1Y9ncC9wARAQAB
            /gcDAgs1a1pU+a2v/8Inj5QH74+FAImr3bNQxyyvB12KpvvqyqoawtRAWP+IdpG8
            pch8aMo8JwIWvzl/YWWEa/mv64eWgcRqHnKzJT3PLFMPkQnYAyTge4LCu2EzR59k
            KDVgF9/M+hrlnFID0bIpO7hdjzwPOVKXtJdo7mD9hoFtUEuDbrk/F/SH30at+KLQ
            EAwcqJwMXUK+atbl1EWteo53y18e1huRPPwcokHz9vSnmE2ZR80ZxTqQ/AVPWEJQ
            YAIt0dVUX+MvPpiwtBf74+benRLoVfP4GesxTe87gh/PavyYuPk9g+kAsYXxGqDM
            awx3fP+JnweXg9YeBEPoOHsYfxAtpMMNhpR0WmWAcOGFjUd0VanwO8/4CJkoJaUO
            zEriYO9IzHptp50NPL5gvPrLOMDJZtE3uWmY8afcv+OUabnFYL8UJ1YmMyPopcVU
            6rF/sAjTRAy5hZiPLkN4ykcX73zbg2tdj7GRq9IV4l//s29HtpGSGZS9P2FJafrv
            L876Lf2awDI3NFkaopyQKKL05P6Flh2E+mJo2592yN1KiBzpJmaDdaPJ6KC+27nr
            dq4FxWzU6aGkNewQE0SksOG19Q0+9RCc68AGwP+nf7OrhgcVerxT9E7cHFFMMxAM
            GLa3ePGMmsWWylXbz9pUKX4hiAtt+frEJfBbt6EnBhknkFkOe64xmO8pSwZToTEl
            sgkkMlj7+OUiwkd65bHEWAedNu9H6CAfsyOBU3//VwI0G83vqf3gpifHUqlOv+QD
            t0ZEmzK2IuQemzr1/F/IW9I80zf7Mm0f8AnRBj+MpZsChpxim6Eo1f9uGREYmFhi
            rQm+DP8nrJiYvQIwWBNDAXrU9awl7wsvMwPEhwt7Rin+UlkbGz8urxW3bnq5EFiI
            zRyo7URwTMwiu4D7+WoXDrlefCzFCDhPT0brNJpp5DU2qJhnZQWw2Szp0ve9keHb
            0gwecOcZR2LOHzKoJPGi87OtS8mFEaEGiOmHr65Vcryw/aF2Oj7wj9ztIt0VygbW
            fHLnszcE9IB7rB6bpPTeMjzhTfB4aVO1NkBlpnCExXozWTR8u8Yh+9ztKdFKaqs2
            JAD4U2qnR6AFQ2foeK0u94aTwdAumS3lVdUPWhbcNuIoVwsBMJfMxwvZgT7yfecg
            Va93WuuH/QKZPNh3erjDLDWFztpbY0qsxiu/s13JhsigreLilyUTGtzvFY/mdRbN
            PbkK7IPeBXhZUETCI6DgqZMI/ZAgX+rkDVzEVBTovOV2bMLoH5DHoLq0teIdTek9
            PZKR3ckrCUf9nnSoOyNKv6ubhMXtMzWIgiEv8UAky48rWfWdAreWwYVCQuTwf9kz
            9zqUo0OkE1A7vu7ZLeBmSgxXgnnbpqIYsN+ircpDMrIzdjoL6XC3ZJEBnvhiNn1t
            R6si9HPOqs1zCjYBJi4now/OWv0Pl7UAdMgdp3r1tJ5+nja7bsJojsGBFNfzWG/6
            eco59nyeDtr4GMd4SRG2iFE8k3jH3ViLFpJ/W1rfMlPync1TPuKXhFYw0912PRiU
            awXOT0SSBrvCmq5Wzi56xDpx8RBLAefjUG2giTcH+lRai+YEsG7ksrEwLpWJL41T
            1hejrDWlZLVqs3q1mjdgDQ1BFvkV/mLvKHTAnhIk4iOqFaT2StAdIxzAJovvqGQ7
            Ux0qlGyFRdPh601UnlX1PrZiebpZT4aermbQ0BxWfIia+ipz5Jj0Bj8Zuy6NLT5V
            3+cERFmPlYCgINbeqXOU/ceQdGEbUBYjNzAz9Iknd8/3zj6PyQEgery0IVBLdW1h
            ciAoT0spIDxrMDdwcmluY2VAZ21haWwuY29tPokCTgQTAQoAOBYhBCUkFk/6Ylbt
            cYoUrA1FQS0qFsfGBQJoLKykAhsDBQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAAAoJ
            EA1FQS0qFsfG+zgP/3PsGYpHCQF8RfmPjlSWHiLC33pC0hLgsaxpq5RQYjkwFb5D
            2Be9lEM0OV6G9PAA6jYlfsjvWitAP92ljObWRbQvK/blxc30Oyn7hx0dDx7Bm8hA
            mAhZcHEFuk5ioU3sBoIDEgS87lyrQHXyp6l1EOsrtpUqXbvzNeJP2D59Fm7Bnb1A
            LqDB4JiLiEXx0CVS4bbKC6VYa2qfcx4dfsb+ufogi/+37N9trDjPg1zgT5y3MJpd
            iktZ7nUegQD+mFAnH3v7E/eQ7gbtq6arpMJpHaFjk/BxXPAKoFGmFUKuv+5ouH+Q
            71KsVuwiagXLzRBhMhaYvBxMP8g2Xz9oNxNbGYN7drvt3iK2FEjct7m/Zes4NFwu
            wYLYLo2zC0Yn77Ekbt3ZEHcQpe49bZFFcrW+o1w/xdTbYzhLnwA15hhlx70b/hzJ
            FyOP7HF2O5j3tovneRXq9gveJAESX6UMcclnl7owTXttTypUlCj1f7v9me+oZZmV
            Ml4w7lj3Sd9WjbvydNcOzHsBrO7+7akd8Je6L07PEBP/pKCzwxL+rOgjRD4hKCQH
            ZIbvYs/UkG+wBrKH7OfeppHMDlFT8ey/2kYOZw3mr1eHVXMOqgGLBNhu7eUgJ92F
            DEDgQkg+abF2AENfgDUykPVo+dLVzVnb6DBcWHKiaOhupVLENga8vfd7KlginQdG
            BGgsrKQBEADAIBvq8W7nEBc4mrsM1XfWuRugodJE1/NqJXg0n2CGN0qxScGogOw8
            S5RYkVGWzDro4foGrtm5e5Gx+nAfVGx4A/0VUGK0fO8ZJcLT8zUn7PobK+nBN4qm
            9E6ezB9M30SOpDfkCDW1nKr9wV0dRwXsqa1lS9JGGSJDQHNXJjJKIBDL0yI8VtWW
            GfJoFtKYar0/Cf9TcxR/WpG1TfFsRnUOJpA/68DFo+dBRfYupilATzYV7cMs8e7H
            I982CjZyOvFQzekU0lPfi0gXNw+QxWtwki1FXAlyZ6eJiuU7zBgYoT0VdV9v6TU8
            hbhR5M6dZvnt7L7QjX3zE77yw3l+c4BDf/r+TMIeHqcTapQGOvEUaL+sVNIi4idN
            l+mBNTNR2S9Dvobe1jkZy0d7ElJSlqpIijeGCsQIYHc9/qFH/WGW8aCYG3wmb22i
            q7u34ukNDNy6Ey/vwTyll9SW8iYT9mk4Nu2w0rGHtmAoyVizTjofspvgXBzKQcyx
            LlakvogJQKVy26BAqIf2/g3R99ANPe5HyaKa/pMe5vxcgWJLJbPNCJFHq5EBfTlg
            lq+wtyeqUM6x9qNlQIz6SCnCwcW4st633UO3C74LB23G38KCz2Sk0rjUmW4cX7GK
            me4nQvxfajvgqm9njmtkvQ3O1Zjz6dxQTmmqRk2hNJ58V1WFvj5kQwARAQAB/gcD
            ApGhK0higYUD/+tCTYynDjO963H/g2urYmrGeyZ3BvIy0iTBk7ioCzemXQTFzdJL
            N2SERWPD+5byE9xwRpisrkBr4FPOUjMKdCGTfKioYYedajyAKMXq82kfkbiWuQvX
            b+UsovNR59eoEb5RTXiqA1SQ7l9OQB1xlWhQ5GqeJNN1OFIl+lOFGMu5qS56epZ9
            g3VS7Vr3ml6s5v3RFqyIDxtrGE9KVB/vkTd3+GXH87IRFHQuz6nxigxYRZy4zq0a
            kx+RH0XusjA2Tprn0JXlsucQBBqGkXkRWDJ72l8hiPGPDEpmxvQihykH+Kmih0Zq
            8TU4q0q1c73VUf/WLmvYLU+MW6j1/c6JnhjshSfCy09mckPVjZ0LNQ0xgWmH9aZK
            yTZirFak+k1rn42I4WXRepnPSem16GxbW2NTslb2dVtC3no1v3fwI5dXlH3xWCIl
            Nd2iW9FwdAexx1EXS8sdpt1MTXT+o2xcJNw6HyFyZMITxwNjYQh0i9VB0pJMjFAR
            kt2poq724Gtrri4npGnFdlc3y/FexL1NlaswnLXQHrklOX9TSPE8Xv8MBmdq1GfV
            xUt2rC8N0cb5s1FQI1gTS30qkPFC+9SoLMTKhS1HeKzubw3D/RHtnBPnLY8do7km
            jECf1Yr25WJ0V1XwI4C29TDHc8qabDp8CFKjXPKWzDWQbpXP2Z8Vx67Tt0AJuMgh
            sV7K9OM4PnAypmhIjg30C+FeIyOWhilmQkKB8EjGKPAZhUSDM3FIhWzOVa2hgsJN
            AFTj8FriZyQffjVXJW5PgNyaULBoR0s2V+7muinuJz9R+VcJ3rKqVmJdbtshqaOr
            k3QwMvEHMhDx/iX2Aq2S6xt3tzYji9SAUtBv7dredLSTCWh1XFEV6Sm/105XueBT
            +73F1O1hw/eqVxg5uJ11mtl7Eukl+rfRsuX6IwMgyQYQR7IIxNEBtck06kcblQ2Y
            KpR7hY7keV81t43G4tpy5J9FsYcCMmLt2SjdXiJUMhDKqv9TtlUfT1N2CZUksgLR
            tni2lFVPwW5xjjaNQZcJ1odynDbkVN7uLvWBF88E00i5/v1ofMq7fSCBhM+UVKBL
            J2pSxY/CrH9tgY4blvMZ8EFQIfMge8cH/FeZy3snwuis7CENE13pQ8nZQO9CFYXg
            UCs3GSvosr1ac1EHIkuAHuY8bfNwV6nJcPoWplt8sAAEQlg+wH2htKMcoXoaSsuf
            eBAjIjBu+xIWKHffqVNhFmTTcwCqzlpnUikiSdHir5ezb+l+PM9lRFRLgBFImvW6
            RAd4He+4K6k9bjB/S0jKm1ikoFMh3uweWXsRn0I7t91My/gtWHzhYcW/yrPkEWWt
            VIuf6brfZaQCeEiBqDHGJBl8oXPJGD+eOgzZxz/CZSO/tjnh01XF1Tteqp1faKin
            xbH+km45OhOCZuu3IqXl89vOSRiQZnrUsHk94qT5rVaCIdaM4DxVUIniQFXlfAsV
            jafmnSDBueOPIAO2UolCuMavI1cCLYSGlfrQkhh0iceDPljYN7mimyyoktXD71V0
            5ZqHB9olhHEVwSjgMWihlIwCJwgWU4bnQnKpbS5K6fSmGyDcX5aaJPQv6ukIKBVN
            pN+GA6xncxaGUyq7s5FwyThKrBApjUdPcDO7F94vWz+5AV0BpSl5kBMyKG8hEquS
            nnAiVaAnuYuK8h90kesqgiIhE142W8UsQ5hc/hp/WAr/KWzrPNtVjcPjf1Tr3UZT
            I+yKBrhdEj7bBXTgBKfm1mkCq4U2G9e1rtfn1cGLNT67+wvNnfKJAjYEGAEKACAW
            IQQlJBZP+mJW7XGKFKwNRUEtKhbHxgUCaCyspAIbDAAKCRANRUEtKhbHxgxcD/9e
            yRAWf93lL0LmVYYtkl3fmFbgXbyanXYjIhMMMDsbT9r7+1Qr6GMjyngK8rOw1Kyy
            N9WeaWdbWzb7PWM9PaojgSOf9BeHxpgWAwMvwNiwHCkIy7bRxQDcdbDwhKBSZ3EB
            5PebFgTrtWB23gHlARUn4lL81/PlxnnvX5oV1ObByjzMHThl9YufXq043O8s5dUO
            YCS7Ew+LKO/ukQqEnAHLtcXbuz1xph7AUOIZr0d/LlNTtnrm5g4LdBIjHIH93Y+m
            hEnoqYaNzDAVdoPZlPtlSbxbeUTDUyxCK+8R/hbUY8AnU6kxqwqu3T3b+D5HdGTO
            yL9ZX7a+f0PLKE8hq0DDLnexWoX8QxpuqTWz1b+xi2sTWPF/Derg3raejRPnWL26
            jmIX8qzmHzIZBOMy78YB2B5znHmG+z+luX8/l/M+PRy1wUzUYQrFuXwwKzw8BoOM
            xOTLPND68jmKIfshiOyYjsA1C7BYO93tkYKi0DlRDtwXDU/f2b5BRnB4NMzESA1K
            S1KDMzisd+dF49Fy4n6JByP8oXZoBTL0ZGC/2ciCjREIcNZr0aAvmwpSOP4kQWNt
            /7cA0/KBSrCkfwWFda8NGB2RN9+y6RA3qcVPBIuPHcPegYc1Xrg1Cq8NA+SsAZu/
            q39p/1PsZ8UMC174Wqn11RJbaJxVx8g3o2Y6WQt0eA==
            =YdZf
            -----END PGP PRIVATE KEY BLOCK-----
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Run GoReleaser on tag
        uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552
        with:
          distribution: goreleaser
          version: latest
          args: release --timeout 60m --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER: ${{ github.actor }}
          EMAIL: ${{ github.actor}}@users.noreply.github.com
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}

      - name: Set up Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and push charts
        run: |
          chartVersion=$(echo ${{ github.ref_name }} | cut -c 2-)

          sed -i "s/^KUBESTELLAR_VERSION:.*$/KUBESTELLAR_VERSION: \"${chartVersion}\"/g" ${{ env.CORE_CHART_PATH }}/values.yaml

          helm package ${{ env.CORE_CHART_PATH }} --destination . --version ${chartVersion} --app-version ${chartVersion} --dependency-update
          helm push ./core-chart*.tgz oci://${{ env.REGISTRY }}/kubestellar/kubestellar
